name: Flat

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'
    # - cron: '0 9 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.10.x

      - name: Checkout code
        uses: actions/checkout@master

      - name: Fetch All Tokopedia Trends
        run: |
           echo MONGO_DB_URI=$MONGO_DB_URI >> .env
           deno run -q --allow-read --allow-write --allow-run --allow-net --allow-env --unstable fetch-trends.ts
        env:
          MONGO_DB_URI: ${{ secrets.MONGO_DB_URI}}
