name: Flat

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    #- cron: '*/5 * * * *'
    - cron: '0 9 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.22.x

      - name: Checkout code
        uses: actions/checkout@master

      - name: Fetch All Tokopedia Trends
        run: |
           echo MONGO_URI=$MONGO_URI >> .env
           echo GH_TOKEN=$GH_TOKEN >> .env
           export $(cat .env | xargs)
           deno run -q --allow-read --allow-write --allow-run --allow-net --allow-env --unstable fetch_trends.ts
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
